### ISSUE TITLE
Optimizer crashing during atlas

### ISSUE THREAD

**Issue by madjin** [M3-org/CharacterStudio#153]
happens when trying to optimize a file that maybe is too many textures to atlas. perhaps could implement better error handling and print a console log message for files that file so batch processing can continue

```
VRMExporterv0.js:1162 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at new MeshData (VRMExporterv0.js:1162:34)
    at VRMExporterv0.js:224:39
    at Array.forEach (<anonymous>)
    at VRMExporterv0.parse (VRMExporterv0.js:219:16)
    at download-utils.js:314:14
    at new Promise (<anonymous>)
    at parseVRM (download-utils.js:244:10)
    at getVRMData (download-utils.js:137:10)
```

**Comment by madjin** [comment]
looks like its fixed now
